#!/usr/bin/env php
<?php

/*
 * This file is part of the ActiveCollab Console utility.
 */

/**
 * @author Kosta Harlan <kostajh@gmail.com>
 */

// installed via composer?
if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

use ActiveCollabConsole\Console\Application;

$application = new Application();
$application->run();
